language: ruby
rvm:
  - "2.3.3"
script:
  - RAILS_ENV=test bundle exec rails db:create db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database boxesapi_test;' -U postgres